FROM python:3.13.1-slim

WORKDIR /app

# Copy requirements first for better caching
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code
COPY . .

CMD ["celery", "-A", "workers.celery_worker", "worker", "--loglevel=info"]
