global:
  scrape_interval: 15s  # How often to scrape targets by default.

scrape_configs:
  - job_name: "fastapi-app"
    static_configs:
      - targets: ["web:8000"]  # Replace with the FastAPI container's address and port
