# version: "3.8"
# services:
#   postgres:
#     image: postgres
#     container_name: helios
#     environment:
#       POSTGRES_USER: chatdocuser
#       POSTGRES_PASSWORD: PassWord@!23
#       PGDATA: /var/lib/postgresql/data
#     volumes:
#       - pgdata:/var/lib/postgresql/data
#     ports:
#       - "5432:5432" # Expose PostgreSQL on host port 5432
# volumes:
#   pgdata:

version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: chatdocuser
      POSTGRES_PASSWORD: PassWord123
      POSTGRES_DB: chatdocdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network

volumes:
  postgres_data:

networks:
  postgres_network:
    driver: bridge
