# kubernetes-ansible/roles/common/vars/main.yml

# Kubernetes version (use a stable, supported version)
kubernetes_version: "1.32.5" # As of May 2025, 1.32.5 is the latest patch for 1.32
kubernetes_apt_repo_version: "v1.32"

# Containerd Cgroup Driver
containerd_cgroup_driver: "systemd"

# Pod Network CIDR (Cilium default or as configured)
pod_network_cidr: "10.244.0.0/16"
