"""Update tables

Revision ID: 4128eb1d3a1c
Revises: 7c85e3dd660f
Create Date: 2025-01-14 10:02:22.769453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision: str = '4128eb1d3a1c'
down_revision: Union[str, None] = '7c85e3dd660f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'date_of_birth')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('date_of_birth', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
