"""Update tables

Revision ID: 416dde55211e
Revises: 4128eb1d3a1c
Create Date: 2025-01-14 15:05:33.832491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '416dde55211e'
down_revision: Union[str, None] = '4128eb1d3a1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('user_created', sa.String(length=255), nullable=True))
    op.add_column('posts', sa.Column('user_updated', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('user_created', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('user_updated', sa.String(length=255), nullable=True))
    op.drop_column('users', 'deleted_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('users', 'user_updated')
    op.drop_column('users', 'user_created')
    op.drop_column('posts', 'user_updated')
    op.drop_column('posts', 'user_created')
    # ### end Alembic commands ###
