"""Add verification token expiration to users

Revision ID: 6b388aae9a10
Revises: baffd7dc0c29
Create Date: 2025-02-17 11:31:57.353450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision: str = '6b388aae9a10'
down_revision: Union[str, None] = 'baffd7dc0c29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verification_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verification_token_expires_at')
    # ### end Alembic commands ###
