# kubernetes-ansible/roles/app_deployment/files/ovh-credentials-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: ovh-credentials-secret
  namespace: cert-manager
type: Opaque
stringData:
  applicationKey: "dd*******"
  applicationSecret: "8153*******"
  consumerKey: "e210906*******"